config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :bank_accounts
  
  namespace :api do
    namespace :v1 do
      post 'bank_accounts/new_transaction', to: 'bank_accounts#new_transaction'
    end
  end
end

app/models/account_transaction.rb
class AccountTransaction < ApplicationRecord
  belongs_to :bank_account
  TRANSACTION_TYPES = ['withdraw', 'deposit']

  validates :bank_account, presence: true
  validates :amount, presence: true, numericality: true
  validates :transaction_type, presence: true, inclusion: { in: TRANSACTION_TYPES }
  validates :transaction_number, presence: true, uniqueness: true

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.transaction_number = SecureRandom.uuid
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :client
  has_many :account_transactions
  validates :client, presence: true
  validates :balance, presence: true, numericality: true
  before_create :generate_bank_account_number, unless: :account_number?

  before_validation :load_defaults

  def load_defaults
    if self.new_record?
      self.balance = 0
    end
  end

  def to_s
    account_number
  end

  private

  def generate_bank_account_number
    self.account_number = Uuid::GeneratorNumber.get_number(self.class.count)
  end
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :bank_accounts, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :middle_name, presence: true
  validates :email, presence: true, uniqueness: true

  before_create :generate_cliente_number, unless: :client_number?
  before_save :format_name

  def format_name
    self.first_name  = self.first_name.upcase
    self.last_name   = self.last_name.upcase
    self.middle_name = self.middle_name.upcase
  end

  def to_s
    "#{last_name}, #{first_name} #{middle_name}"
  end

  private

  def generate_cliente_number
    self.client_number = Uuid::GeneratorNumber.get_number(self.class.count)
  end
end

app/controllers/api/v1/bank_accounts_controller.rb
module Api
  module V1
    class BankAccountsController < ApplicationController
      skip_before_action :verify_authenticity_token
      def new_transaction
        amount           = params[:amount]
        transaction_type = params[:transaction_type]
        bank_account_id  = params[:bank_account_id]

        errors = BankAccounts::ValidateNewTransaction.new(
                amount: amount,
                transaction_type: transaction_type,
                bank_account_id: bank_account_id
        ).execute!

        if errors.size > 0
          render json: {errors: errors }, status: 402
        else
          bank_account = BankAccounts::PerformTransaction.new(
                        amount: amount,
                        transaction_type: transaction_type,
                        bank_account_id: bank_account_id
          ).execute!
          render json: {balance: bank_account.balance }
        end

      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  def index
    @bank_accounts = BankAccount.all
  end
  def show
    @bank_account = BankAccount.find(params[:id])
  end
  def new
    @bank_account = BankAccount.new
  end
  def create
    @bank_account = BankAccount.new(bank_account_params)
    if @bank_account.save
      redirect_to bank_account_path(@bank_account.id)
    else
      render 'new'
    end
  end
  def edit
  end
  def update
  end
  def destroy
  end

  private
  def bank_account_params
    params.require(:bank_account).permit(:client_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def number_of_accounts
    BankAccount.count
  end
  def number_of_clients
    Client.count
  end
  def number_to_money(number)
    if number > 0
      number / 100.00
    else
      0.00
    end
  end
  def money_to_number(money)
    money * 100
  end

end

app/views/bank_accounts/_modal_transaction.haml
#parameters{ data: {bank_account_id: @bank_account.id } }

#modal-transaction.modal.fade.modal-fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{type:'button', data:{dismiss:'modal'}}
          %span{aria:{hidden:'true'}}
            %i.fa.fa-close
          %span.sr-only Close
        %h4.modal-title
          New Transaction
      .modal-body
        .row
          .col-xs-12
            .notification
        .row
          .col-xs-6
            %label
              Amount
            = text_field_tag :amount, 0.00, id: 'input-amount', class: 'form-control'
          .col-xs-6
            %label
              Transaction Type
            = select_tag :transaction_type, options_for_select(AccountTransaction::TRANSACTION_TYPES), id: 'select-transaction-type', class: 'form-control'
      .modal-footer
        %button.btn.btn-default{type:'button', data:{dismiss:'modal'}} Close
        %button#btn-save.btn.btn-primary{type:'button'} Save

app/views/bank_accounts/_transactions.haml
%table.table.table-bordered
  %thead
    %tr
      %th Date of transaction
      %th Transaction type
      %th.text-right Amount
  %tbody
    - bank_account.account_transactions.each do |transaction|
      %tr
        %td #{transaction.created_at}
        %td #{transaction.transaction_type}
        %td.text-right #{number_to_currency(number_to_money(transaction.amount), unit: Money::ConstantsIdentity.money_unit )}
    %tr
      %th
      %th Balance
      %th.text-right #{number_to_currency(number_to_money(bank_account.balance), unit: Money::ConstantsIdentity.money_unit )}

app/views/bank_accounts/index.html.haml
.container
  .row
    .col-md-12
      %h1
        Bank Accounts @result
      = link_to new_bank_account_path, class: 'btn btn-primary' do
        New Bank Account
  %table.table.table-bordered
    %thead
      %tr
        %th Account Number
        %th Client
        %th Balance
        %th Actions
    %tbody
      - @bank_accounts.each do |bank_account|
        %tr
          %td #{bank_account.account_number}
          %td #{bank_account.client}
          %td #{number_to_currency(number_to_money(bank_account.balance), unit: '$ ')}
          %td
            = link_to bank_account_path(bank_account.id), class: "btn btn-primary" do
              Show

app/views/bank_accounts/new.html.haml
.container
  .row
    .col-xs-12
    %h1
      New Bank Account
    = simple_form_for @bank_account do |f|
      .form-group
        = f.input :account_number, input_html: {class: 'form-control'}
      .form-group
        = f.association :client, input_html: {class: 'form-control'}, prompt: "Choose a Client"
      .form-actions
        = button_tag type: :submit, class: 'btn btn-primary' do
          Save Bank Account
        = link_to root_path, class: 'btn btn-default' do
          Cancel

app/views/bank_accounts/show.html.haml
.container
  .row
    .col-xs-12
      %h1
        Account number: #{ @bank_account.account_number}
        %small
          #{ @bank_account.client}
      = button_tag :new_transaction, id: 'btn-new-transaction', class: 'btn btn-primary' do
        New Transaction

      = link_to bank_accounts_path, class: 'btn btn-default' do
        Back to Bank Accounts

.container
  .row
    .col-xs-12

      = render partial: 'transactions', locals: { bank_account: @bank_account}

= render partial: 'modal_transaction'
= javascript_include_tag 'bank_accounts/show'
:javascript
  $(function() {
    Show.init();
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bank</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.haml
.container
  .row
    .col-md-12
      %h1
        My Bank
      %h2
        Number of Accounts: #{number_of_accounts}
      %h2
        Number of Clients: #{number_of_clients}
  .row
    .col-md-12
      = link_to bank_accounts_path do
        Bank Accounts
      = link_to new_bank_account_path do
        New Bank Account